### ISSUE TITLE
How to get a specific wishlist like product by id

### ISSUE THREAD

**Issue by sohil123123** [lamalamaNL/laravel-wishlist#6]
How to get a specific wishlist like product by id

**Comment by lamalamaMark** [comment]
Can you give a little more context around your question? Would like to answer but don't understand the question.

**Comment by sohil123123** [comment]
for example "A" user add product "abc" and product "xyz" in wishlist

than i need "A" user product "abc" Wishlist

**Comment by lamalamaMark** [comment]
The Model is added to a 'default' wishlist (see databse) when you don't specify a wishlist when you add a model to the wishlist.

You can retrieve the default wishlist via `$user->wishlist();`
